language: node_js
node_js:
  - "node"

before_script:
  - npm install cpr

script: npm run build

before_deploy:
  - cd dist/lib

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true

  on:
    tags: true

